### ISSUE TITLE
Skills. Добавить навыки, которые помогают экономить steps персонажа.

### ISSUE THREAD

**Issue by A1ekseyN** [A1ekseyN/2Walks#5]
Добавить в игру навыки, которые помогают экономить steps при выборе активности.
Это отдельные навыки, которые за +1 прокачанный навык помогают сэкономить 1% от необходимого количества шагов для активности.

**Навыки для добавления в игру:** 
- [x] Оптимизация движений: Adventure
- [x] Оптимизация движений: Gym
- [x] Оптимизация движений: Work

**Добавить навыки для прокачки в Спортзале:**
- [x] Оптимизация движений: Adventure
- [x] Оптимизация движений: Gym
- [x] Оптимизация движений: Work
 
**Интегрировать навык в расчёт количества шагов, которые нужны для активности:**
- [x] Оптимизация движений: Adventure
- [x] Оптимизация движений: Gym
- [x] Оптимизация движений: Work
